#include "games/yacht.hpp"

#include "audio_catalog.hpp"

#include <numeric>

namespace mf {

namespace {

constexpr unsigned kSourceTicksPerNativeTick = 2;

// CODE 18 $2F22 lays out Pak 6011's twelve 96x20 score-line controls at
// (378,54), advancing twenty pixels per row.  The controls belong to the
// player's right scorecard; the left scorecard is Mario's and is not input.
constexpr int kPlayerScoreLineLeft = 378;
constexpr int kPlayerScoreLineTop = 54;
constexpr int kPlayerScoreLineWidth = 96;
constexpr int kPlayerScoreLineHeight = 20;
constexpr int kScoreLineCount = 12;

// CODE 18 $2B42/$2C40 creates two authored die lanes.  Flag-zero dice are
// white and are removed/regenerated by $2A8E/$2ADC; flag-one dice move down
// into the red lane and remain held.  This is true even though index 16's
// shipped prompt describes selecting dice "to roll again."
constexpr std::array<int, 5> kDieLefts{154, 195, 236, 277, 318};
constexpr int kRerollDieTop = 261;
constexpr int kHeldDieTop = 284;
constexpr int kDieWidth = 39;
constexpr int kDieHeight = 38;

// CODE 18 registers every Macintosh Yacht gameplay actor against the same
// center-stage origin.  The DOS HostAnimation callbacks below deliberately
// retain their edition-specific coordinates.
constexpr Point kMacYachtHostAnchor{15, -1};
constexpr Point kMacYachtTorsoAnchor{26, 0};
// Movie 6021's time-zero base/overlay records share a destination. These
// inputs place that destination at the source idle-control origins: (217,18)
// on Macintosh and (119,9) on DOS. The animated gesture has a separate
// controller registration and continues to use kMacYachtHostAnchor.
constexpr Point kMacYachtIdleMovieAnchor{24, 2};
constexpr Point kDosYachtIdleMovieAnchor{-281, -94};
constexpr Point kMacYachtCupAnchor{218, 129};
constexpr Point kMacYachtRollMovieAnchor{0, -9};
constexpr Rect kMacYachtRollButton{218, 129, 296, 228};
// Preserve the previously source-verified DOS hit rectangle exactly instead
// of deriving it from the corrected Macintosh registration.
constexpr Rect kDosYachtRollButton{135, 86, 184, 140};

constexpr std::array<std::array<int, 5>, 4> kYachtIdleJokes{{
    {{11455, 11456, 11459, 11460, 11461}},
    {{11455, 11456, 11709, 11710, 11711}},
    {{11455, 11456, 11724, 11725, 11726}},
    {{11455, 11456, 11727, 11728, 11729}},
}};

bool sourcePraiseEligible(int category, int score) {
    // CODE 18 $1E5A receives the scorecard's top-to-bottom category index.
    // Convert the native Aces..Yacht order to Yacht..Aces before applying
    // its literal category-specific thresholds.
    const int sourceCategory = 11 - category;
    switch (sourceCategory) {
    case 0: return score == 50;  // Yacht
    case 1: return score == 30;  // Big straight
    case 2: return score == 25;  // Little straight
    case 3:
    case 4: return score > 0;    // Four of a kind / full house
    case 5: return score > 20;   // Choice
    case 6: return score > 12;   // Sixes
    case 7: return score > 10;   // Fives
    case 8: return score > 8;    // Fours
    case 9: return score > 6;    // Threes
    case 10: return score > 4;   // Deuces
    case 11: return score > 2;   // Aces
    default: return false;
    }
}

std::wstring_view sourceYachtMovieText(int movie) {
    switch (movie) {
    case 11412: return L"Select the line to score.";
    case 11413: return L"Select a different line to score.";
    case 11414: return L"You can't go there!";
    case 11416: return L"Select the dice to roll again.";
    case 11421: return L"Oh brother!";
    case 11422: return L"Okay!";
    case 11424: return L"Oh no!";
    case 11425: return L"Uh oh!";
    case 11427: return L"Hoo hoo! A Yacht!";
    case 11429: return L"Hmm...";
    case 11430: return L"Let's see...";
    case 11431: return L"I got it...";
    case 11434: return L"I'm going to roll these ones again.";
    case 11437: return L"Mamma mia...";
    case 11438: return L"Hey, what's taking so long?";
    case 11446: return L"That's a good move!";
    case 11447: return L"That's a great move!";
    case 11448: return L"Way to go!";
    case 11451: return L"I really enjoy playing with you.";
    case 11452: return L"Oh, you're so good!";
    default: return L"";
    }
}

}  // namespace

int yachtScoreCategoryAt(Point point) {
    if (point.x < kPlayerScoreLineLeft ||
        point.x >= kPlayerScoreLineLeft + kPlayerScoreLineWidth ||
        point.y < kPlayerScoreLineTop ||
        point.y >= kPlayerScoreLineTop + kPlayerScoreLineHeight * kScoreLineCount) {
        return -1;
    }
    const int sourceRow = (point.y - kPlayerScoreLineTop) / kPlayerScoreLineHeight;
    return 11 - sourceRow;
}

Rect yachtDieRect(int index, bool held) {
    if (index < 0 || index >= static_cast<int>(kDieLefts.size())) return {};
    const int left = kDieLefts[static_cast<std::size_t>(index)];
    const int top = held ? kHeldDieTop : kRerollDieTop;
    return {left, top, left + kDieWidth, top + kDieHeight};
}

int yachtRemainingRollMarkers(int completedRolls, bool rollPending) {
    return std::clamp(3 - completedRolls - (rollPending ? 1 : 0), 0, 3);
}

bool yachtComputerRerollSpeechEligible(int rollsRemaining,
                                       const std::array<bool, 5>& held) {
    // CODE 18 $16E2 requires rolls remaining, an adviser reroll, and $227C > 1.
    // $227C counts flag-zero white dice, including the all-five-white case.
    return rollsRemaining > 0 && std::count(held.begin(), held.end(), false) > 1;
}

bool yachtHasWhiteDieToReroll(const std::array<bool, 5>& held) {
    return std::any_of(held.begin(), held.end(), [](bool heldDie) { return !heldDie; });
}

YachtGame::YachtGame(GameContext context)
    : Game(context), host_(context.assets, context.graphics, context.audio, true,
          [](int resourceId, Point scaled) {
              if (resourceId >= 10000) return Point{118, 1};
              return scaled;
          }),
      rollAnimation_(context.assets, context.graphics, context.audio),
      gestureAnimation_(context.assets, context.graphics, context.audio, true,
          [](int resourceId, Point scaled) {
              if (resourceId == 6021) return Point{-258, -90};
              return scaled;
          }),
      idleActorMovie_(context.assets, 6021),
      outcomeAnimation_(context.assets, context.graphics, context.audio) {
    // CODE 18 $318C initializes the four-joke cursor once when the Yacht
    // module is loaded.  $142E increments it before every joke.
    idleJokeIndex_ = context_.random.below(4000) / 1000;
    reset();
}

std::wstring_view YachtGame::categoryName(int category) {
    static constexpr std::array<std::wstring_view, 12> names{
        L"Aces", L"Deuces", L"Threes", L"Fours", L"Fives", L"Sixes",
        L"Choice", L"Full house", L"Four of a kind", L"Little straight", L"Big straight", L"Yacht"};
    return names[static_cast<std::size_t>(category)];
}

int YachtGame::categoryMovie(int category) {
    // CODE 18 stores the spoken score-line names in descending display order:
    // Big Straight through Aces use 11400..11410. Yacht uses its separate
    // source clip (sound 6006) at movie 11470.
    if (category == 11) return 11470;
    if (category < 0 || category > 10) return -1;
    return 11410 - category;
}

void YachtGame::reset() {
    host_.stop();
    rollAnimation_.stop();
    gestureAnimation_.stop();
    outcomeAnimation_.stop();
    humanScores_.fill(-1); computerScores_.fill(-1); dice_.fill(1); held_.fill(false);
    computerTargetHeld_.fill(false);
    rolls_ = round_ = winner_ = 0;
    outcomeDelayTicks_ = outcomeClearTick_ = outcomeVisibleDiceCount_ = 0;
    outcomePhase_ = OutcomePhase::None;
    introPhase_ = IntroPhase::GoodLuck;
    introGapSourceTicks_ = 0;
    openingDelayMilliseconds_ = 1;
    showComputerDice_ = false;
    pendingComputerAfterSpeech_ = false;
    pendingScoreReactionMovie_ = -1;
    pendingComputerRerollSpeech_ = false;
    pendingRollPlayer_ = 0;
    settlingDieIndex_ = 0;
    computerAttempt_ = computerRerollStage_ = computerSelectionCursor_ = 0;
    computerSelectionDelaySourceTicks_ = 0;
    computerReadyCategory_ = -1;
    pendingComputerScoreCategory_ = -1;
    computerScoreDelaySourceTicks_ = 0;
    computerAnnouncementCount_ = 0;
    idlePhase_ = IdlePhase::Waiting;
    idleElapsedSourceTicks_ = 0;
    idleTargetSourceTicks_ = 80;
    idleGapSourceTicks_ = 0;
    idleJokePart_ = 0;
    status_ = L"Good luck!";
    // $AD2 speaks index 11, waits five controller ticks, then index 18.
    host_.play(11411, kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
}

bool YachtGame::tick() {
    bool changed = host_.tick();
    changed = rollAnimation_.tick() || changed;
    changed = gestureAnimation_.tick() || changed;
    changed = outcomeAnimation_.tick() || changed;
    changed |= tickIntro();
    if (introPhase_ != IntroPhase::Complete) {
        return changed;
    }

    if (pendingScoreReactionMovie_ >= 0) {
        // CODE 18 records the score click through tracked $A18 sound 5003,
        // then reaches the reaction movie on a later controller state. Keep
        // the movie's time-zero voice from replacing the click in the same
        // native event.
        if (!context_.audio.directSoundBusy()) {
            const int movie = std::exchange(pendingScoreReactionMovie_, -1);
            host_.play(movie, kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
        }
        return true;
    }

    const auto beginComputerRerollGesture = [this]() {
        status_.clear();
        gestureAnimation_.play(6021, kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
        context_.audio.playSound(5010);
        computerRerollStage_ = 6;
    };

    if (pendingRollPlayer_ != 0 && !rollAnimation_.active()) {
        const int player = pendingRollPlayer_;
        if (settlingDieIndex_ < static_cast<int>(dice_.size())) {
            bool settled = false;
            while (settlingDieIndex_ < static_cast<int>(dice_.size()) && !settled) {
                const std::size_t index = static_cast<std::size_t>(settlingDieIndex_++);
                const bool reroll = player > 0 ? rolls_ == 0 || !held_[index]
                                               : computerAttempt_ == 0 || !held_[index];
                if (!reroll) continue;
                dice_[index] = context_.random.below(30000) / 5000 + 1;
                // $192C skips held flags in the same pass; $196E settles one
                // regenerated white die per controller pass.
                context_.audio.playSound(5019);
                settled = true;
            }
        } else {
            pendingRollPlayer_ = 0;
            settlingDieIndex_ = 0;
            if (player > 0) resolveHumanRoll();
            else resolveComputerRoll();
        }
        changed = true;
    } else if (pendingComputerAfterSpeech_ && !host_.active()) {
        pendingComputerAfterSpeech_ = false;
        // Player controller $1256 clears the dice after Mario's reaction,
        // then $126E advances the completed round. Mario opens each round.
        showComputerDice_ = false;
        dice_.fill(1);
        held_.fill(false);
        computerTargetHeld_.fill(false);
        rolls_ = 0;
        advanceRound();
        if (winner_) beginOutcome();
        else beginComputerRoll();
        changed = true;
    } else if (computerRerollStage_ == 1) {
        if (computerSelectionDelaySourceTicks_ > kSourceTicksPerNativeTick) {
            computerSelectionDelaySourceTicks_ -= kSourceTicksPerNativeTick;
        } else {
            computerSelectionDelaySourceTicks_ = 0;
            while (computerSelectionCursor_ < static_cast<int>(held_.size()) &&
                   held_[static_cast<std::size_t>(computerSelectionCursor_)] ==
                       computerTargetHeld_[static_cast<std::size_t>(computerSelectionCursor_)]) {
                ++computerSelectionCursor_;
            }
            if (computerSelectionCursor_ < static_cast<int>(held_.size())) {
                const std::size_t index = static_cast<std::size_t>(computerSelectionCursor_++);
                held_[index] = computerTargetHeld_[index];
                // $164E/$168C changes one control, plays 5028, and waits five
                // source ticks before asking the adviser for the next index.
                context_.audio.playSound(5028);
                computerSelectionDelaySourceTicks_ = 5;
            } else if (yachtComputerRerollSpeechEligible(3 - computerAttempt_, held_) &&
                       context_.random.below(4000) / 1000 < 1) {
                pendingComputerRerollSpeech_ = true;
                computerRerollStage_ = 2;
                status_ = sourceYachtMovieText(11434);
                host_.play(11434, kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
            } else {
                beginComputerRerollGesture();
            }
        }
        changed = true;
    } else if (computerRerollStage_ == 2 && !host_.active()) {
        beginComputerRerollGesture();
        changed = true;
    } else if (computerRerollStage_ == 3 && !host_.active()) {
        // $182A waits for both announcement clips, then inserts a two-tick
        // pause before the scorecard write at $1848.
        computerScoreDelaySourceTicks_ = 2;
        computerRerollStage_ = 7;
        changed = true;
    } else if (computerRerollStage_ == 4 && !host_.active()) {
        status_.clear();
        computerRerollStage_ = 1;
        changed = true;
    } else if (computerRerollStage_ == 5 && !host_.active()) {
        const int category = computerReadyCategory_;
        computerReadyCategory_ = -1;
        computerRerollStage_ = 0;
        finishComputerTurn(category);
        changed = true;
    } else if (computerRerollStage_ == 6 && !gestureAnimation_.active()) {
        continueComputerReroll();
        changed = true;
    } else if (computerRerollStage_ == 7) {
        if (computerScoreDelaySourceTicks_ > kSourceTicksPerNativeTick) {
            computerScoreDelaySourceTicks_ -= kSourceTicksPerNativeTick;
        } else {
            computerScoreDelaySourceTicks_ = 9;
            const int category = pendingComputerScoreCategory_;
            if (category >= 0 && category < static_cast<int>(computerScores_.size())) {
                computerScores_[static_cast<std::size_t>(category)] =
                    yachtCategoryScore(category, dice_);
                context_.audio.playSound(5003);
            }
            computerRerollStage_ = 8;
        }
        changed = true;
    } else if (computerRerollStage_ == 8) {
        if (computerScoreDelaySourceTicks_ > kSourceTicksPerNativeTick) {
            computerScoreDelaySourceTicks_ -= kSourceTicksPerNativeTick;
        } else {
            pendingComputerScoreCategory_ = -1;
            computerScoreDelaySourceTicks_ = 0;
            computerRerollStage_ = 0;
            computerAttempt_ = 0;
            computerSelectionCursor_ = 0;
            computerSelectionDelaySourceTicks_ = 0;
            showComputerDice_ = false;
            dice_.fill(1);
            held_.fill(false);
            computerTargetHeld_.fill(false);
            if (!winner_) status_ = L"It's your turn!";
        }
        changed = true;
    }
    changed |= tickOutcome();
    const bool waitingForPlayer = !winner_ && openingDelayMilliseconds_ == 0 &&
        pendingRollPlayer_ == 0 && !rollAnimation_.active() &&
        !gestureAnimation_.active() && !host_.active() && computerRerollStage_ == 0;
    changed |= tickSourceIdle(waitingForPlayer);
    return changed;
}

bool YachtGame::tickIntro() {
    if (introPhase_ == IntroPhase::Complete) return false;

    const auto beginInitialMarioRoll = [&]() {
        introPhase_ = IntroPhase::Complete;
        openingDelayMilliseconds_ = 0;
        beginComputerRoll();
    };

    switch (introPhase_) {
    case IntroPhase::GoodLuck:
        if (host_.active()) return false;
        introGapSourceTicks_ = 5;
        introPhase_ = IntroPhase::GoodLuckGap;
        return true;
    case IntroPhase::GoodLuckGap:
        if (introGapSourceTicks_ > static_cast<int>(kSourceTicksPerNativeTick)) {
            introGapSourceTicks_ -= static_cast<int>(kSourceTicksPerNativeTick);
            return true;
        }
        status_ = L"I go first.";
        host_.play(11418, kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
        introPhase_ = IntroPhase::IGoFirst;
        return true;
    case IntroPhase::IGoFirst:
        if (host_.active()) return false;
        introGapSourceTicks_ = 2;
        introPhase_ = IntroPhase::IGoFirstGap;
        return true;
    case IntroPhase::IGoFirstGap:
        if (introGapSourceTicks_ > static_cast<int>(kSourceTicksPerNativeTick)) {
            introGapSourceTicks_ -= static_cast<int>(kSourceTicksPerNativeTick);
            return true;
        }
        // $CF8 chooses whether Mario also says index 20 before his first roll.
        if (context_.random.below(2000) / 1000 == 0) {
            introGapSourceTicks_ = 2;
            introPhase_ = IntroPhase::OptionalTurnGap;
        } else {
            beginInitialMarioRoll();
        }
        return true;
    case IntroPhase::OptionalTurnGap:
        if (introGapSourceTicks_ > static_cast<int>(kSourceTicksPerNativeTick)) {
            introGapSourceTicks_ -= static_cast<int>(kSourceTicksPerNativeTick);
            return true;
        }
        status_ = L"It's my turn now.";
        host_.play(11420, kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
        introPhase_ = IntroPhase::OptionalTurnSpeech;
        return true;
    case IntroPhase::OptionalTurnSpeech:
        if (host_.active()) return false;
        beginInitialMarioRoll();
        return true;
    case IntroPhase::Complete:
        return false;
    }
    return false;
}

void YachtGame::scheduleNextSourceIdle() {
    idleTargetSourceTicks_ = 80;
    idleElapsedSourceTicks_ = 0;
    idlePhase_ = IdlePhase::Waiting;
}

void YachtGame::cancelSourceIdle() {
    if (idlePhase_ != IdlePhase::Waiting) host_.stop();
    idlePhase_ = IdlePhase::Waiting;
    idleElapsedSourceTicks_ = 0;
    idleTargetSourceTicks_ = 80;
    idleGapSourceTicks_ = 0;
    idleJokePart_ = 0;
}

bool YachtGame::tickSourceIdle(bool eligible) {
    switch (idlePhase_) {
    case IdlePhase::Waiting: {
        if (!eligible) {
            idleElapsedSourceTicks_ = 0;
            return false;
        }
        idleElapsedSourceTicks_ += kSourceTicksPerNativeTick;
        if (idleElapsedSourceTicks_ < idleTargetSourceTicks_ || host_.active()) return false;
        idleElapsedSourceTicks_ = 0;

        // $1018/$10EC use a 75/25 single-line/joke split.
        const int branch = context_.random.below(4000) / 1000;
        if (branch < 3) {
            const bool first = context_.random.below(2000) / 1000 == 0;
            const bool rollsRemain = rolls_ < 3;
            const int movie = rollsRemain ? (first ? 11438 : 11437)
                                          : (first ? 11412 : 11437);
            status_ = sourceYachtMovieText(movie);
            host_.play(movie, kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
            idlePhase_ = IdlePhase::SingleLine;
        } else {
            idleJokeIndex_ = (idleJokeIndex_ + 1) % 4;
            idleJokePart_ = 0;
            idleGapSourceTicks_ = 5;
            status_ = L"Knock knock...";
            host_.play(kYachtIdleJokes[static_cast<std::size_t>(idleJokeIndex_)][0],
                       kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
            idlePhase_ = IdlePhase::Joke;
        }
        return true;
    }
    case IdlePhase::SingleLine:
        if (host_.active()) return false;
        scheduleNextSourceIdle();
        return true;
    case IdlePhase::Joke:
        if (host_.active()) return false;
        if (idleJokePart_ >= 4) {
            scheduleNextSourceIdle();
            return true;
        }
        if (idleGapSourceTicks_ > kSourceTicksPerNativeTick) {
            idleGapSourceTicks_ -= kSourceTicksPerNativeTick;
            return true;
        }
        idleGapSourceTicks_ = 5;
        ++idleJokePart_;
        host_.play(kYachtIdleJokes[static_cast<std::size_t>(idleJokeIndex_)]
                                 [static_cast<std::size_t>(idleJokePart_)],
                   kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
        return true;
    }
    return false;
}

void YachtGame::roll() {
    if (rolls_ >= 3 || winner_ || openingDelayMilliseconds_ > 0 ||
        pendingRollPlayer_ || rollAnimation_.active() || gestureAnimation_.active() ||
        host_.active() || computerRerollStage_ != 0) return;
    if (rolls_ > 0 && !yachtHasWhiteDieToReroll(held_)) {
        // Player controller $113C calls $227C and rejects a zero-white-die
        // reroll with dialogue index 16. All-five-white rerolls remain legal.
        status_ = sourceYachtMovieText(11416);
        host_.play(11416, kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
        return;
    }
    // The first roll changes all five.  Later rolls regenerate flag-zero
    // white dice and preserve flag-one red dice; rerolling all five is legal.
    rollAnimation_.play(6020,
                        dosEdition() ? -26 : kMacYachtRollMovieAnchor.x,
                        dosEdition() ? 53 : kMacYachtRollMovieAnchor.y);
    pendingRollPlayer_ = 1;
    settlingDieIndex_ = 0;
    context_.audio.playSound(5018);
    status_.clear();
}

void YachtGame::resolveHumanRoll() {
    showComputerDice_ = false;
    ++rolls_;
    status_ = rolls_ < 3 ? L"Select dice to roll again, or select a line to score." :
                           L"Select the line to score.";
}

void YachtGame::beginComputerRoll() {
    if (winner_) return;
    held_.fill(false);
    computerTargetHeld_.fill(false);
    rolls_ = 0;
    computerAttempt_ = computerRerollStage_ = computerSelectionCursor_ = 0;
    computerSelectionDelaySourceTicks_ = 0;
    computerReadyCategory_ = -1;
    pendingComputerScoreCategory_ = -1;
    computerScoreDelaySourceTicks_ = 0;
    pendingComputerRerollSpeech_ = false;
    showComputerDice_ = false;
    status_ = L"Mario's turn.";
    // Computer controller $D84 creates movie 6021 before every roll. Its
    // authored 5044 cue and the direct 5010 effect precede pipe movie 6020.
    gestureAnimation_.play(6021, kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
    context_.audio.playSound(5010);
    computerRerollStage_ = 6;
}

int yachtCategoryScore(int category, const std::array<int, 5>& dice) {
    std::array<int, 7> counts{};
    const int sum = std::accumulate(dice.begin(), dice.end(), 0);
    for (int value : dice) ++counts[value];
    if (category < 6) return counts[category + 1] * (category + 1);
    if (category == 6) return sum;
    if (category == 7) {
        bool pair = false, triple = false;
        for (int value = 1; value <= 6; ++value) { pair |= counts[value] == 2; triple |= counts[value] == 3; }
        return pair && triple ? sum : 0;
    }
    if (category == 8) return std::any_of(counts.begin(), counts.end(), [](int count) { return count >= 4; }) ? sum : 0;
    if (category == 9) {
        for (int first = 1; first <= 3; ++first)
            if (counts[first] && counts[first + 1] && counts[first + 2] && counts[first + 3])
                return 25;
        return 0;
    }
    if (category == 10)
        return ((counts[1] && counts[2] && counts[3] && counts[4] && counts[5]) ||
                (counts[2] && counts[3] && counts[4] && counts[5] && counts[6])) ? 30 : 0;
    return std::any_of(counts.begin(), counts.end(), [](int count) { return count == 5; }) ? 50 : 0;
}

namespace {

std::array<int, 7> yachtCounts(const std::array<int, 5>& dice) {
    std::array<int, 7> counts{};
    for (int value : dice) ++counts[static_cast<std::size_t>(value)];
    return counts;
}

// CODE 18's adviser uses this order internally, which is not the native
// scorecard order: Aces..Sixes, Four Kind, Full House, Little Straight,
// Big Straight, Yacht, Choice.
constexpr std::array<int, 12> kSourceToNativeCategory{
    0, 1, 2, 3, 4, 5, 8, 7, 9, 10, 11, 6
};

bool sourceCategoryOpen(int sourceCategory, const std::array<int, 12>& scores) {
    return scores[static_cast<std::size_t>(kSourceToNativeCategory[sourceCategory])] < 0;
}

int sourceTripleValue(const std::array<int, 7>& counts) {
    for (int value = 1; value <= 6; ++value)
        if (counts[value] >= 3) return value;
    return 0;
}

std::array<int, 2> sourcePairValues(const std::array<int, 7>& counts) {
    std::array<int, 2> result{};
    int found = 0;
    for (int value = 1; value <= 6 && found < 2; ++value)
        if (counts[value] >= 2) result[found++] = value;
    return result;
}

int sourceConsecutiveLength(int value, const std::array<int, 7>& counts) {
    int length = 1;
    while (length < 6 && value + length <= 6 && counts[value + length] > 0) ++length;
    return length;
}

int sourceLongestRun(const std::array<int, 5>& dice,
                     const std::array<int, 7>& counts,
                     int* firstValue = nullptr) {
    int bestLength = 0;
    int bestFirst = 0;
    for (int value : dice) {
        const int length = sourceConsecutiveLength(value, counts);
        if (length > bestLength) {
            bestLength = length;
            bestFirst = value;
        }
    }
    if (firstValue) *firstValue = bestFirst;
    return bestLength;
}

std::array<int, 12> sourceAdviserScores(const std::array<int, 5>& dice) {
    const auto counts = yachtCounts(dice);
    std::array<int, 12> result{};
    int sum = 0;
    for (int value = 1; value <= 6; ++value) {
        result[value - 1] = counts[value] * value;
        sum += result[value - 1];
    }
    const bool hasPair = std::any_of(counts.begin() + 1, counts.end(),
        [](int count) { return count == 2; });
    const bool hasTriple = std::any_of(counts.begin() + 1, counts.end(),
        [](int count) { return count == 3; });
    const int maximum = *std::max_element(counts.begin() + 1, counts.end());
    result[6] = maximum >= 4 ? sum : 0;
    result[7] = hasPair && hasTriple ? 25 : 0;
    const int run = sourceLongestRun(dice, counts);
    result[8] = run >= 4 ? 25 : 0;
    result[9] = run == 5 ? 30 : 0;
    result[10] = maximum == 5 ? 50 : 0;
    result[11] = sum;
    return result;
}

void sourceKeepOnly(std::array<bool, 5>& reroll,
                    const std::array<int, 5>& dice, int value) {
    for (std::size_t index = 0; index < dice.size(); ++index)
        reroll[index] = dice[index] != value;
}

void sourceKeepOnly(std::array<bool, 5>& reroll,
                    const std::array<int, 5>& dice, int first, int second) {
    for (std::size_t index = 0; index < dice.size(); ++index)
        reroll[index] = dice[index] != first && dice[index] != second;
}

int sourceHighestOpenUpperPresent(const std::array<int, 12>& adviserScores,
                                  const std::array<int, 12>& scores) {
    for (int sourceCategory = 5; sourceCategory >= 0; --sourceCategory)
        if (adviserScores[sourceCategory] > 0 && sourceCategoryOpen(sourceCategory, scores))
            return sourceCategory + 1;
    return 0;
}

int sourceReadyCategory(const std::array<int, 5>& dice,
                        const std::array<int, 12>& scores) {
    const auto adviserScores = sourceAdviserScores(dice);
    const auto counts = yachtCounts(dice);
    if (adviserScores[10] > 0 && sourceCategoryOpen(10, scores)) return 11;
    if (adviserScores[9] > 0 && sourceCategoryOpen(9, scores)) return 10;
    if (adviserScores[8] > 0 && sourceCategoryOpen(8, scores) &&
        !sourceCategoryOpen(9, scores)) return 9;
    if (adviserScores[7] > 9 && sourceCategoryOpen(7, scores)) return 7;
    const int triple = sourceTripleValue(counts);
    // `$3790` literally indexes the status table with the one-based die value
    // here (unlike `$3806`, which subtracts one). Preserve that source quirk.
    if (adviserScores[6] > 8 && sourceCategoryOpen(6, scores) &&
        !sourceCategoryOpen(10, scores) && triple > 0 &&
        !sourceCategoryOpen(triple, scores)) return 8;
    return -1;
}

}  // namespace

std::array<bool, 5> yachtComputerRerolls(const std::array<int, 5>& dice,
                                         const std::array<int, 12>& scores) {
    std::array<bool, 5> reroll{};
    if (sourceReadyCategory(dice, scores) >= 0) return reroll;

    const auto counts = yachtCounts(dice);
    const auto adviserScores = sourceAdviserScores(dice);
    const int triple = sourceTripleValue(counts);
    if (triple > 0 && (sourceCategoryOpen(10, scores) || sourceCategoryOpen(6, scores) ||
                       sourceCategoryOpen(triple - 1, scores) || sourceCategoryOpen(7, scores))) {
        sourceKeepOnly(reroll, dice, triple);
        return reroll;
    }

    int straightFirst = 0;
    const int straightLength = sourceLongestRun(dice, counts, &straightFirst);
    const int straightCategory = sourceCategoryOpen(9, scores) ? 9 :
                                 sourceCategoryOpen(8, scores) ? 8 : -1;
    if (straightLength >= 3 && straightCategory >= 0) {
        int special = -1;
        if (straightCategory == 9 && straightFirst == 1) special = 5;
        else if (straightCategory == 9 && straightFirst == 3) special = 2;
        bool specialKept = false;
        std::array<int, 7> keptCounts{};
        for (std::size_t index = 0; index < dice.size(); ++index) {
            const int value = dice[index];
            const bool inRun = value >= straightFirst &&
                               value < straightFirst + straightLength;
            const bool keepSpecial = !inRun && value == special && !specialKept;
            reroll[index] = !inRun && !keepSpecial;
            if (!reroll[index]) {
                ++keptCounts[value];
                specialKept |= keepSpecial;
            }
        }
        // `$3DB0` repeatedly removes the first member of every duplicate,
        // leaving the final source-order occurrence selected.
        for (int value = 1; value <= 6; ++value) {
            int remove = keptCounts[value] - 1;
            for (std::size_t index = 0; index < dice.size() && remove > 0; ++index) {
                if (!reroll[index] && dice[index] == value) {
                    reroll[index] = true;
                    --remove;
                }
            }
        }
        return reroll;
    }

    const auto pairs = sourcePairValues(counts);
    if (pairs[0] > 0 && pairs[1] > 0 && sourceCategoryOpen(7, scores)) {
        sourceKeepOnly(reroll, dice, pairs[0], pairs[1]);
        return reroll;
    }

    const int highestUpper = sourceHighestOpenUpperPresent(adviserScores, scores);
    for (const int pair : {pairs[1], pairs[0]}) {
        if (pair == 0) continue;
        if (sourceCategoryOpen(pair - 1, scores) || sourceCategoryOpen(7, scores) ||
            sourceCategoryOpen(6, scores)) {
            sourceKeepOnly(reroll, dice, pair);
            return reroll;
        }
        if (highestUpper >= 4) {
            sourceKeepOnly(reroll, dice, highestUpper);
            return reroll;
        }
        if (sourceCategoryOpen(10, scores)) {
            sourceKeepOnly(reroll, dice, pair);
            return reroll;
        }
    }

    if (highestUpper > 0) {
        sourceKeepOnly(reroll, dice, highestUpper);
        return reroll;
    }
    reroll.fill(true);
    return reroll;
}

std::array<bool, 5> yachtComputerHeldDice(const std::array<int, 5>& dice,
                                          const std::array<int, 12>& scores) {
    auto held = yachtComputerRerolls(dice, scores);
    for (bool& value : held) value = !value;
    return held;
}

int yachtComputerCategory(const std::array<int, 5>& dice,
                          const std::array<int, 12>& scores) {
    if (const int ready = sourceReadyCategory(dice, scores); ready >= 0) return ready;
    const auto counts = yachtCounts(dice);
    const auto adviserScores = sourceAdviserScores(dice);
    int firstOpen = -1;
    int lastPositive = -1;
    int bestSource = -1;
    int bestScore = -999;
    for (int sourceCategory = 0; sourceCategory < 12; ++sourceCategory) {
        if (!sourceCategoryOpen(sourceCategory, scores)) continue;
        if (firstOpen < 0) firstOpen = sourceCategory;
        if (adviserScores[sourceCategory] > bestScore) {
            bestScore = adviserScores[sourceCategory];
            bestSource = sourceCategory;
        }
        if (adviserScores[sourceCategory] > 0) lastPositive = sourceCategory;
    }
    if (firstOpen < 0) return -1;
    if (lastPositive < 0) lastPositive = firstOpen;

    // Four Kind through Yacht are accepted immediately. Upper lines and
    // Choice pass through CODE 18's triple/pair and low-line sacrifice rules.
    if (bestSource < 6 || bestSource == 11) {
        const int triple = sourceTripleValue(counts);
        if (triple > 0 && sourceCategoryOpen(triple - 1, scores)) {
            bestSource = triple - 1;
        } else if (bestSource < 6 || bestScore < 20) {
            int openPairUpper = -1;
            for (int sourceCategory = 0; sourceCategory < 6; ++sourceCategory) {
                if (counts[sourceCategory + 1] == 2 &&
                    sourceCategoryOpen(sourceCategory, scores)) {
                    openPairUpper = sourceCategory;
                    break;
                }
            }
            bestSource = openPairUpper >= 0 ? openPairUpper : lastPositive;
            if (bestSource >= 3 && firstOpen < 2) bestSource = firstOpen;
        }
    }
    return kSourceToNativeCategory[bestSource];
}

int YachtGame::total(const std::array<int, 12>& scores) const {
    int result = 0;
    for (int score : scores) if (score >= 0) result += score;
    return result;
}

void YachtGame::scoreHuman(int category) {
    if (rolls_ == 0 || category < 0 || category >= 12) return;
    if (humanScores_[category] >= 0) {
        // The already-filled-line path at $82C uses an equal index 13/14 draw.
        const int movie = context_.random.below(2000) / 1000 == 0 ? 11413 : 11414;
        status_ = sourceYachtMovieText(movie);
        host_.play(movie, kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
        return;
    }

    const int score = yachtCategoryScore(category, dice_);
    humanScores_[category] = score;
    context_.audio.playSound(5003);

    int movie = 11422;  // $1226: the source's low/zero-score "Okay!"
    if (category == 11 && score == 50) {
        movie = 11427;
    } else if (sourcePraiseEligible(category, score)) {
        if (total(humanScores_) > total(computerScores_)) {
            // $11EE first chooses between praise and Mario-frustration, then
            // $190 lazily shuffles the selected three-entry pool.
            if (context_.random.below(2000) / 1000 == 0) {
                movie = drawDialoguePool(positiveReactionPool_, positiveReactionPoolCursor_);
            } else {
                movie = drawDialoguePool(worriedReactionPool_, worriedReactionPoolCursor_);
            }
        } else {
            movie = drawDialoguePool(friendlyReactionPool_, friendlyReactionPoolCursor_);
        }
    }
    status_ = sourceYachtMovieText(movie);
    pendingComputerAfterSpeech_ = true;
    pendingScoreReactionMovie_ = movie;
}

void YachtGame::resolveComputerRoll() {
    ++computerAttempt_;
    showComputerDice_ = false;
    beginComputerSelection();
}

int YachtGame::drawDialoguePool(std::vector<int>& movies, std::size_t& cursor) {
    if (cursor >= movies.size()) {
        sourceShuffle(movies, context_.random);
        cursor = 0;
    }
    return movies[cursor++];
}

void YachtGame::beginComputerSelection() {
    computerReadyCategory_ = computerAttempt_ >= 3
        ? yachtComputerCategory(dice_, computerScores_)
        : sourceReadyCategory(dice_, computerScores_);
    computerTargetHeld_ = held_;
    if (computerReadyCategory_ < 0) {
        computerTargetHeld_ = yachtComputerHeldDice(dice_, computerScores_);
    }
    computerSelectionCursor_ = 0;
    computerSelectionDelaySourceTicks_ = 0;

    // $15C8 draws below 3000 after every computer roll, including the final
    // one. Two outcomes enter $190's shuffled Hmm/Let's see/I got it pool.
    if (context_.random.below(3000) / 1000 < 2) {
        const int movie = drawDialoguePool(thinkingPool_, thinkingPoolCursor_);
        status_ = sourceYachtMovieText(movie);
        host_.play(movie, kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
        computerRerollStage_ = computerReadyCategory_ >= 0 ? 5 : 4;
        return;
    }

    if (computerReadyCategory_ >= 0) {
        const int category = computerReadyCategory_;
        computerReadyCategory_ = -1;
        finishComputerTurn(category);
        return;
    }
    computerRerollStage_ = 1;
}

void YachtGame::continueComputerReroll() {
    pendingComputerRerollSpeech_ = false;
    computerRerollStage_ = 0;
    computerSelectionCursor_ = 0;
    computerSelectionDelaySourceTicks_ = 0;
    showComputerDice_ = false;
    rollAnimation_.play(6020,
                        dosEdition() ? -26 : kMacYachtRollMovieAnchor.x,
                        dosEdition() ? 53 : kMacYachtRollMovieAnchor.y);
    pendingRollPlayer_ = -1;
    settlingDieIndex_ = 0;
    context_.audio.playSound(5018);
    status_.clear();
}

void YachtGame::finishComputerTurn(int preferredCategory) {
    const int bestCategory = preferredCategory >= 0
        ? preferredCategory : yachtComputerCategory(dice_, computerScores_);
    if (bestCategory < 0) return;
    pendingComputerScoreCategory_ = bestCategory;
    computerScoreDelaySourceTicks_ = 0;
    showComputerDice_ = true;
    // CODE 18 alternates the two source lead-ins before speaking the line.
    host_.play((++computerAnnouncementCount_ & 1) ? 11432 : 11435,
               kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
    if (const int movie = categoryMovie(bestCategory); movie >= 0) host_.queue(movie);
    status_ = L"Mario puts " + std::to_wstring(yachtCategoryScore(bestCategory, dice_)) + L" on the " +
              std::wstring(categoryName(bestCategory)) + L" line. Your roll.";
    computerRerollStage_ = 3;
}

void YachtGame::advanceRound() {
    ++round_;
    if (round_ < 12) return;
    const int human = total(humanScores_); const int computer = total(computerScores_);
    winner_ = human == computer ? 2 : (human > computer ? 1 : -1);
    status_ = winner_ == 2 ? L"It's a tie!" : winner_ > 0 ? L"Congratulations! You win!" :
                                                      L"Looks like Mario wins this time!";
}

void YachtGame::beginOutcome() {
    if (!winner_ || outcomePhase_ != OutcomePhase::None) return;
    outcomeVisibleDiceCount_ = 0;
    int movie = 0;
    if (winner_ == 2) movie = 11442;                         // CODE 18 index 42
    else if (winner_ > 0)
        movie = context_.random.below(2000) / 1000 ? 11445 : 11444;
    else movie = context_.random.below(2000) / 1000 ? 11443 : 11439;
    if (host_.active()) host_.queue(movie);
    else host_.play(movie, kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
    outcomePhase_ = OutcomePhase::Announcement;
}

bool YachtGame::finished() const {
    return outcomePhase_ == OutcomePhase::Complete;
}

bool YachtGame::tickOutcome() {
    if (outcomePhase_ == OutcomePhase::None || outcomePhase_ == OutcomePhase::Complete) {
        return false;
    }
    switch (outcomePhase_) {
    case OutcomePhase::Announcement:
        if (host_.active()) return false;
        if (winner_ > 0 && winner_ != 2) {
            context_.audio.playMusic(audio_catalog::playerWinMusic(dosEdition(), 4));
            showComputerDice_ = true;
            held_.fill(false);
            outcomeVisibleDiceCount_ = 0;
            outcomePhase_ = OutcomePhase::VictoryDice;
        } else {
            outcomeDelayTicks_ = 9;
            outcomePhase_ = OutcomePhase::PreReplayDelay;
        }
        return true;
    case OutcomePhase::VictoryDice:
        // $1B16 creates one white die per controller pass. The fifth pass
        // immediately starts the player-only celebration movie 6022.
        if (outcomeVisibleDiceCount_ < static_cast<int>(dice_.size())) {
            const std::size_t index = static_cast<std::size_t>(outcomeVisibleDiceCount_);
            dice_[index] = outcomeVisibleDiceCount_ + 1;
            ++outcomeVisibleDiceCount_;
        }
        if (outcomeVisibleDiceCount_ >= static_cast<int>(dice_.size())) {
            outcomeAnimation_.play(6022, 69, 69);
            outcomePhase_ = OutcomePhase::Celebration;
        }
        return true;
    case OutcomePhase::Celebration:
        if (outcomeAnimation_.active()) return false;
        outcomeDelayTicks_ = 2;
        outcomePhase_ = OutcomePhase::PreReplayDelay;
        return true;
    case OutcomePhase::PreReplayDelay:
        if (outcomeDelayTicks_-- > 0) return true;
        // $1B8C uses index 53 for every result: the replay question.
        host_.play(11453, kMacYachtHostAnchor.x, kMacYachtHostAnchor.y);
        outcomePhase_ = OutcomePhase::ReplayPrompt;
        return true;
    case OutcomePhase::ReplayPrompt:
        if (host_.active()) return false;
        outcomeDelayTicks_ = 2;
        outcomePhase_ = OutcomePhase::PostReplayDelay;
        return true;
    case OutcomePhase::PostReplayDelay:
        if (outcomeDelayTicks_-- > 0) return true;
        outcomeClearTick_ = 0;
        outcomePhase_ = OutcomePhase::ScorecardClear;
        return true;
    case OutcomePhase::ScorecardClear:
        if (outcomeClearTick_ < 24) {
            const int category = outcomeClearTick_ / 2;
            humanScores_[category] = -1;
            computerScores_[category] = -1;
            if ((category & 1) == 0) context_.audio.playSound(5003);
            ++outcomeClearTick_;
            return true;
        }
        outcomeDelayTicks_ = 9;
        outcomePhase_ = OutcomePhase::FinishDelay;
        return true;
    case OutcomePhase::FinishDelay:
        if (outcomeDelayTicks_-- > 0) return true;
        outcomePhase_ = OutcomePhase::Complete;
        return true;
    case OutcomePhase::None:
    case OutcomePhase::Complete:
        return false;
    }
    return false;
}

bool YachtGame::sourceOutcomeRegressionTest(int expectedWinner) {
    if (expectedWinner != -1 && expectedWinner != 1 && expectedWinner != 2) return false;
    host_.stop();
    openingDelayMilliseconds_ = 0;
    introPhase_ = IntroPhase::Complete;
    pendingRollPlayer_ = 0;
    pendingComputerAfterSpeech_ = false;
    pendingScoreReactionMovie_ = -1;
    computerRerollStage_ = 0;
    winner_ = expectedWinner;
    humanScores_.fill(3);
    computerScores_.fill(2);
    beginOutcome();

    bool sawCelebration = false;
    bool sawVictoryDice = false;
    bool sawReplayPrompt = false;
    bool sawScorecardClear = false;
    for (int tickIndex = 0; tickIndex < 1200 && !finished(); ++tickIndex) {
        (void)tick();
        sawVictoryDice |= outcomePhase_ == OutcomePhase::VictoryDice;
        sawCelebration |= outcomeAnimation_.active();
        sawReplayPrompt |= outcomePhase_ == OutcomePhase::ReplayPrompt;
        sawScorecardClear |= outcomePhase_ == OutcomePhase::ScorecardClear;
    }
    const bool expectCelebration = expectedWinner == 1;
    return winner_ == expectedWinner && finished() && sawReplayPrompt && sawScorecardClear &&
           sawVictoryDice == expectCelebration &&
           sawCelebration == expectCelebration &&
           std::all_of(humanScores_.begin(), humanScores_.end(), [](int score) { return score < 0; }) &&
           std::all_of(computerScores_.begin(), computerScores_.end(), [](int score) { return score < 0; });
}

bool YachtGame::sourceDialogueRegressionTest() {
    static constexpr std::array<std::array<int, 5>, 4> expectedJokes{{
        {{11455, 11456, 11459, 11460, 11461}},
        {{11455, 11456, 11709, 11710, 11711}},
        {{11455, 11456, 11724, 11725, 11726}},
        {{11455, 11456, 11727, 11728, 11729}},
    }};
    if (kYachtIdleJokes != expectedJokes) return false;
    if (!sourcePraiseEligible(11, 50) || sourcePraiseEligible(11, 0) ||
        !sourcePraiseEligible(10, 30) || sourcePraiseEligible(10, 25) ||
        !sourcePraiseEligible(6, 21) || sourcePraiseEligible(6, 20) ||
        !sourcePraiseEligible(0, 3) || sourcePraiseEligible(0, 2)) {
        return false;
    }

    // Seed-one covers the module-load joke selector, opening 50/50 branch,
    // the 2/3 thinking branch, and $190's first lazy four-entry shuffle.
    SourceRandom random(1);
    if (random.below(4000) / 1000 != 3) return false;
    if (random.below(2000) / 1000 != 1) return false;
    if (random.below(3000) / 1000 != 0) return false;
    std::vector<int> thinking{11430, 11429, 11429, 11431};
    sourceShuffle(thinking, random);
    static const std::vector<int> expectedThinking{11429, 11431, 11430, 11429};
    return thinking == expectedThinking && random.seed() == 470211272U;
}

bool YachtGame::sourceComputerSelectionRegressionTest() {
    host_.stop();
    rollAnimation_.stop();
    gestureAnimation_.stop();
    outcomeAnimation_.stop();
    introPhase_ = IntroPhase::Complete;
    openingDelayMilliseconds_ = 0;
    winner_ = 0;
    outcomePhase_ = OutcomePhase::None;
    pendingRollPlayer_ = 0;
    pendingComputerAfterSpeech_ = false;
    pendingScoreReactionMovie_ = -1;
    computerAttempt_ = 1;
    computerRerollStage_ = 1;
    held_ = {false, false, false, false, false};
    computerTargetHeld_ = {true, false, true, false, false};
    computerSelectionCursor_ = 0;
    computerSelectionDelaySourceTicks_ = 0;

    (void)tick();
    if (held_ != std::array<bool, 5>{true, false, false, false, false} ||
        computerSelectionCursor_ != 1 || computerSelectionDelaySourceTicks_ != 5 ||
        computerRerollStage_ != 1) return false;
    (void)tick();
    if (computerSelectionDelaySourceTicks_ != 3 || held_[2]) return false;
    (void)tick();
    if (computerSelectionDelaySourceTicks_ != 1 || held_[2]) return false;
    (void)tick();
    return held_ == std::array<bool, 5>{true, false, true, false, false} &&
           computerSelectionCursor_ == 3 && computerSelectionDelaySourceTicks_ == 5 &&
           computerRerollStage_ == 1;
}

bool YachtGame::sourceTurnOrderRegressionTest() {
    host_.stop();
    rollAnimation_.stop();
    gestureAnimation_.stop();
    outcomeAnimation_.stop();
    introPhase_ = IntroPhase::Complete;
    openingDelayMilliseconds_ = 0;
    outcomePhase_ = OutcomePhase::None;
    winner_ = round_ = 0;
    pendingRollPlayer_ = 0;
    pendingComputerAfterSpeech_ = false;
    pendingScoreReactionMovie_ = -1;
    humanScores_.fill(-1);
    computerScores_.fill(-1);
    dice_ = {1, 1, 1, 1, 1};
    computerAttempt_ = 1;

    finishComputerTurn(0);
    if (round_ != 0 || computerScores_[0] != -1 ||
        pendingComputerScoreCategory_ != 0 || computerRerollStage_ != 3) return false;
    host_.stop();
    (void)tick();
    if (computerRerollStage_ != 7 || computerScores_[0] != -1 || round_ != 0) return false;
    (void)tick();
    if (computerRerollStage_ != 8 || computerScores_[0] != 5 || round_ != 0) return false;
    computerScoreDelaySourceTicks_ = 0;
    (void)tick();
    if (computerRerollStage_ != 0 || round_ != 0) return false;

    humanScores_[0] = 4;
    pendingComputerAfterSpeech_ = true;
    host_.stop();
    (void)tick();
    if (round_ != 1 || winner_ != 0 || pendingRollPlayer_ != 0 ||
        computerRerollStage_ != 6 || !gestureAnimation_.active()) return false;

    rollAnimation_.stop();
    gestureAnimation_.stop();
    pendingRollPlayer_ = 0;
    computerRerollStage_ = 0;
    round_ = 11;
    humanScores_.fill(2);
    computerScores_.fill(1);
    pendingComputerAfterSpeech_ = true;
    host_.stop();
    (void)tick();
    return round_ == 12 && winner_ == 1 && pendingRollPlayer_ == 0 &&
           outcomePhase_ == OutcomePhase::Announcement;
}

bool YachtGame::shouldDrawStationaryCup() const noexcept {
    // Pak 6010 frame 12 is the idle roll control. Movie 6020 owns the large
    // cup from mouse-down until every die has settled. The rule is deliberately
    // edition-neutral: Macintosh and DOS share this controller state.
    return openingDelayMilliseconds_ == 0 && !showComputerDice_ && rolls_ == 0 &&
           computerAttempt_ == 0 && computerRerollStage_ == 0 &&
           pendingRollPlayer_ == 0 && !rollAnimation_.active() &&
           !gestureAnimation_.active() && !host_.active();
}

bool YachtGame::sourceCupPresentationRegressionTest() {
    host_.stop();
    rollAnimation_.stop();
    gestureAnimation_.stop();
    outcomeAnimation_.stop();
    introPhase_ = IntroPhase::Complete;
    openingDelayMilliseconds_ = 0;
    showComputerDice_ = false;
    rolls_ = 0;
    winner_ = 0;
    computerAttempt_ = 0;
    computerRerollStage_ = 0;
    pendingRollPlayer_ = 0;
    held_.fill(false);

    if (!shouldDrawStationaryCup()) return false;
    roll();
    if (pendingRollPlayer_ != 1 || !rollAnimation_.active() ||
        shouldDrawStationaryCup() ||
        context_.audio.lastSampleRequestRoute() != SampleRequestRoute::Tracked ||
        context_.audio.requestedSoundResourceId() != 5018) return false;

    // Exercise the complete live path rather than manufacturing its terminal
    // state. The movie can finish before the five sequential die-settle
    // passes, and the pending controller must continue suppressing the idle
    // cup during every one of them in both resource editions.
    bool sawMovie = false;
    int settledDice = 0;
    for (int tickIndex = 0;
         tickIndex < 256 && (pendingRollPlayer_ != 0 || rollAnimation_.active());
         ++tickIndex) {
        if (shouldDrawStationaryCup()) return false;
        sawMovie = sawMovie || rollAnimation_.active();
        const int previousSettlingIndex = settlingDieIndex_;
        (void)tick();
        if (settlingDieIndex_ > previousSettlingIndex) {
            if (context_.audio.lastSampleRequestRoute() != SampleRequestRoute::Tracked ||
                context_.audio.requestedSoundResourceId() != 5019) return false;
            settledDice += settlingDieIndex_ - previousSettlingIndex;
        }
        if ((pendingRollPlayer_ != 0 || rollAnimation_.active()) &&
            shouldDrawStationaryCup()) return false;
    }
    if (!sawMovie || settledDice != 5 || pendingRollPlayer_ != 0 ||
        rollAnimation_.active() || rolls_ != 1 || shouldDrawStationaryCup()) return false;

    rolls_ = 0;
    showComputerDice_ = true;
    return !shouldDrawStationaryCup();
}

bool YachtGame::sourceFullMatchRegressionTest() {
    const std::uint32_t savedSeed = context_.random.seed();
    const auto fail = [&]() {
        context_.random.setSeed(savedSeed);
        return false;
    };
    constexpr std::array<std::uint32_t, 8> seeds{
        1U, 17U, 0x1234U, 0x4d415249U,
        0x00c0ffeeU, 0x13579bdfU, 0x2468ace0U, 0x7ffffffeU};
    bool sawPlayerRoll = false;
    bool sawPlayerHold = false;
    bool sawPlayerUnhold = false;
    bool sawMarioRoll = false;
    bool sawPlayerScore = false;
    bool sawMarioScore = false;

    const auto scoreIsValid = [](int category, int score) {
        if (score < 0) return score == -1;
        if (category >= 0 && category < 6)
            return score <= 5 * (category + 1) && score % (category + 1) == 0;
        if (category == 6) return score >= 5 && score <= 30;
        if (category == 7 || category == 8) return score == 0 || (score >= 5 && score <= 30);
        if (category == 9) return score == 0 || score == 25;
        if (category == 10) return score == 0 || score == 30;
        return category == 11 && (score == 0 || score == 50);
    };

    for (const std::uint32_t seed : seeds) {
        context_.random.setSeed(seed);
        reset();
        std::array<int, 12> previousHuman = humanScores_;
        std::array<int, 12> previousComputer = computerScores_;
        bool matchSawPlayerRoll = false;
        bool matchSawMarioRoll = false;
        bool matchSawPlayerScore = false;
        bool matchSawMarioScore = false;
        bool matchSawFullScorecards = false;

        const auto stateIsValid = [&]() {
            if (round_ < 0 || round_ > 12 || rolls_ < 0 || rolls_ > 3 ||
                winner_ < -1 || winner_ > 2 || pendingRollPlayer_ < -1 ||
                pendingRollPlayer_ > 1 || settlingDieIndex_ < 0 || settlingDieIndex_ > 5 ||
                computerAttempt_ < 0 || computerAttempt_ > 3 ||
                computerRerollStage_ < 0 || computerRerollStage_ > 8) return false;
            if (std::any_of(dice_.begin(), dice_.end(),
                    [](int die) { return die < 1 || die > 6; })) return false;
            for (int category = 0; category < 12; ++category) {
                if (!scoreIsValid(category, humanScores_[static_cast<std::size_t>(category)]) ||
                    !scoreIsValid(category, computerScores_[static_cast<std::size_t>(category)])) {
                    return false;
                }
            }
            if (round_ < 12) {
                const int humanFilled = static_cast<int>(std::count_if(
                    humanScores_.begin(), humanScores_.end(), [](int score) { return score >= 0; }));
                const int computerFilled = static_cast<int>(std::count_if(
                    computerScores_.begin(), computerScores_.end(), [](int score) { return score >= 0; }));
                if ((humanFilled != round_ && humanFilled != round_ + 1) ||
                    (computerFilled != round_ && computerFilled != round_ + 1) ||
                    computerFilled < humanFilled || computerFilled > humanFilled + 1) return false;
            }
            if ((pendingRollPlayer_ != 0 || rollAnimation_.active()) &&
                shouldDrawStationaryCup()) return false;
            return true;
        };

        // Speech is fast-forwarded, but every state transition is owned by
        // the live intro, roll, die-select, scorecard, Mario-turn, and outcome
        // controllers. Any dead input state therefore reaches the ceiling.
        for (int controllerPass = 0; controllerPass < 20000 && !finished();
             ++controllerPass) {
            host_.stop();
            const bool playerCanAct = !winner_ && introPhase_ == IntroPhase::Complete &&
                openingDelayMilliseconds_ == 0 && pendingRollPlayer_ == 0 &&
                !pendingComputerAfterSpeech_ && !rollAnimation_.active() &&
                !gestureAnimation_.active() && !host_.active() &&
                computerRerollStage_ == 0;
            if (playerCanAct) {
                const Point rollPoint = dosEdition() ? Point{159, 113} : Point{257, 178};
                if (rolls_ == 0) {
                    click(rollPoint);
                    if (pendingRollPlayer_ != 1 || !rollAnimation_.active()) return fail();
                    sawPlayerRoll = matchSawPlayerRoll = true;
                } else if (rolls_ == 1) {
                    for (const int index : {0, 2}) {
                        Rect rect = yachtDieRect(index, held_[static_cast<std::size_t>(index)]);
                        Point point{(rect.left + rect.right) / 2, (rect.top + rect.bottom) / 2};
                        if (dosEdition()) point = {dosX(point.x), dosY(point.y)};
                        click(point);
                        if (!held_[static_cast<std::size_t>(index)]) return fail();
                    }
                    sawPlayerHold = true;
                    click(rollPoint);
                    if (pendingRollPlayer_ != 1 || !rollAnimation_.active()) return fail();
                    sawPlayerRoll = matchSawPlayerRoll = true;
                } else if (rolls_ == 2) {
                    for (const int index : {0, 1}) {
                        const bool wasHeld = held_[static_cast<std::size_t>(index)];
                        Rect rect = yachtDieRect(index, wasHeld);
                        Point point{(rect.left + rect.right) / 2, (rect.top + rect.bottom) / 2};
                        if (dosEdition()) point = {dosX(point.x), dosY(point.y)};
                        click(point);
                        if (held_[static_cast<std::size_t>(index)] == wasHeld) return fail();
                    }
                    sawPlayerUnhold = true;
                    click(rollPoint);
                    if (pendingRollPlayer_ != 1 || !rollAnimation_.active()) return fail();
                    sawPlayerRoll = matchSawPlayerRoll = true;
                } else {
                    int category = -1;
                    int bestScore = -1;
                    for (int candidate = 0; candidate < 12; ++candidate) {
                        if (humanScores_[static_cast<std::size_t>(candidate)] >= 0) continue;
                        const int score = yachtCategoryScore(candidate, dice_);
                        if (score > bestScore) {
                            category = candidate;
                            bestScore = score;
                        }
                    }
                    if (category < 0) return fail();
                    const int sourceRow = 11 - category;
                    Point point{kPlayerScoreLineLeft + kPlayerScoreLineWidth / 2,
                                kPlayerScoreLineTop + sourceRow * kPlayerScoreLineHeight +
                                    kPlayerScoreLineHeight / 2};
                    if (dosEdition()) point = {dosX(point.x), dosY(point.y)};
                    click(point);
                    if (humanScores_[static_cast<std::size_t>(category)] != bestScore ||
                        !pendingComputerAfterSpeech_ || pendingScoreReactionMovie_ < 0 ||
                        context_.audio.lastSampleRequestRoute() != SampleRequestRoute::Tracked ||
                        context_.audio.requestedSoundResourceId() != 5003) return fail();
                    sawPlayerScore = matchSawPlayerScore = true;
                }
            }

            const int pendingBefore = pendingRollPlayer_;
            (void)tick();
            sawMarioRoll |= pendingBefore == -1 || pendingRollPlayer_ == -1;
            matchSawMarioRoll |= pendingBefore == -1 || pendingRollPlayer_ == -1;

            for (int category = 0; category < 12; ++category) {
                const std::size_t index = static_cast<std::size_t>(category);
                const auto changedLegally = [&](int previous, int current) {
                    if (previous < 0) return current < 0 || current >= 0;
                    if (current == previous) return true;
                    return current < 0 && (outcomePhase_ == OutcomePhase::ScorecardClear ||
                                           outcomePhase_ == OutcomePhase::Complete);
                };
                if (!changedLegally(previousHuman[index], humanScores_[index]) ||
                    !changedLegally(previousComputer[index], computerScores_[index])) return fail();
                if (previousComputer[index] < 0 && computerScores_[index] >= 0) {
                    sawMarioScore = matchSawMarioScore = true;
                }
            }
            previousHuman = humanScores_;
            previousComputer = computerScores_;
            matchSawFullScorecards |=
                std::all_of(humanScores_.begin(), humanScores_.end(), [](int score) { return score >= 0; }) &&
                std::all_of(computerScores_.begin(), computerScores_.end(), [](int score) { return score >= 0; });
            if (!stateIsValid()) return fail();
        }

        if (!finished() || winner_ == 0 || round_ != 12 || !matchSawPlayerRoll ||
            !matchSawMarioRoll || !matchSawPlayerScore || !matchSawMarioScore ||
            !matchSawFullScorecards || !stateIsValid()) return fail();
    }

    context_.random.setSeed(savedSeed);
    return sawPlayerRoll && sawPlayerHold && sawPlayerUnhold && sawMarioRoll &&
           sawPlayerScore && sawMarioScore;
}

bool YachtGame::sourceReplayRegressionTest() {
    const std::uint32_t savedSeed = context_.random.seed();
    thinkingPool_ = {11431, 11429, 11430, 11429};
    positiveReactionPool_ = {11447, 11448, 11446};
    worriedReactionPool_ = {11425, 11421, 11424};
    friendlyReactionPool_ = {11452, 11451};
    thinkingPoolCursor_ = 2;
    positiveReactionPoolCursor_ = 1;
    worriedReactionPoolCursor_ = 2;
    friendlyReactionPoolCursor_ = 1;
    idleJokeIndex_ = 3;
    const auto thinkingPool = thinkingPool_;
    const auto positivePool = positiveReactionPool_;
    const auto worriedPool = worriedReactionPool_;
    const auto friendlyPool = friendlyReactionPool_;
    humanScores_.fill(50);
    computerScores_.fill(30);
    dice_ = {2, 3, 4, 5, 6};
    held_.fill(true);
    rolls_ = 3;
    round_ = 12;
    winner_ = 1;
    computerAnnouncementCount_ = 9;
    outcomePhase_ = OutcomePhase::Complete;
    animatedPieces_ = false;
    context_.playerIsYoshi = false;

    resetForReplay();

    const bool valid =
        std::all_of(humanScores_.begin(), humanScores_.end(), [](int score) { return score == -1; }) &&
        std::all_of(computerScores_.begin(), computerScores_.end(), [](int score) { return score == -1; }) &&
        std::all_of(dice_.begin(), dice_.end(), [](int die) { return die == 1; }) &&
        std::none_of(held_.begin(), held_.end(), [](bool held) { return held; }) &&
        rolls_ == 0 && round_ == 0 && winner_ == 0 && outcomePhase_ == OutcomePhase::None &&
        introPhase_ == IntroPhase::GoodLuck && openingDelayMilliseconds_ == 1 &&
        pendingRollPlayer_ == 0 && computerRerollStage_ == 0 &&
        computerAnnouncementCount_ == 0 && host_.active() && host_.activeResourceId() == 11411 &&
        !rollAnimation_.active() && !gestureAnimation_.active() && !outcomeAnimation_.active() &&
        thinkingPool_ == thinkingPool && thinkingPoolCursor_ == 2 &&
        positiveReactionPool_ == positivePool && positiveReactionPoolCursor_ == 1 &&
        worriedReactionPool_ == worriedPool && worriedReactionPoolCursor_ == 2 &&
        friendlyReactionPool_ == friendlyPool && friendlyReactionPoolCursor_ == 1 &&
        idleJokeIndex_ == 3 && !animatedPieces_ && !context_.playerIsYoshi &&
        context_.random.seed() == savedSeed;
    context_.random.setSeed(savedSeed);
    return valid;
}

void YachtGame::setQaVictoryPresentation() {
    host_.stop();
    openingDelayMilliseconds_ = 0;
    introPhase_ = IntroPhase::Complete;
    pendingRollPlayer_ = 0;
    pendingComputerAfterSpeech_ = false;
    pendingScoreReactionMovie_ = -1;
    computerRerollStage_ = 0;
    winner_ = 1;
    humanScores_.fill(12);
    computerScores_.fill(8);
    for (std::size_t index = 0; index < dice_.size(); ++index) {
        dice_[index] = static_cast<int>(index) + 1;
    }
    showComputerDice_ = true;
    outcomeVisibleDiceCount_ = 5;
    outcomeAnimation_.play(6022, 69, 69);
    outcomePhase_ = OutcomePhase::Celebration;
    status_ = L"Congratulations! You win!";
}

void YachtGame::setQaScorecardPresentation() {
    host_.stop();
    rollAnimation_.stop();
    gestureAnimation_.stop();
    outcomeAnimation_.stop();
    openingDelayMilliseconds_ = 0;
    introPhase_ = IntroPhase::Complete;
    pendingRollPlayer_ = 0;
    pendingComputerAfterSpeech_ = false;
    pendingScoreReactionMovie_ = -1;
    pendingComputerRerollSpeech_ = false;
    computerAttempt_ = 0;
    computerRerollStage_ = 0;
    computerReadyCategory_ = -1;
    winner_ = 0;
    outcomePhase_ = OutcomePhase::None;
    humanScores_.fill(-1);
    computerScores_.fill(-1);
    humanScores_[0] = 3;
    humanScores_[3] = 12;
    humanScores_[6] = 20;
    humanScores_[11] = 50;
    computerScores_[1] = 4;
    computerScores_[4] = 15;
    computerScores_[7] = 18;
    computerScores_[10] = 30;
    dice_ = {1, 2, 3, 4, 5};
    held_.fill(false);
    rolls_ = 1;
    showComputerDice_ = false;
    status_ = L"Select dice to roll again, or select a line to score.";
    cancelSourceIdle();
}

void YachtGame::setQaDiceSelectionPresentation() {
    setQaScorecardPresentation();
    humanScores_.fill(-1);
    computerScores_.fill(-1);
    dice_ = {4, 2, 3, 3, 4};
    held_ = {false, false, true, true, true};
    rolls_ = 1;
    status_ = L"Select the dice to roll again.";
}

void YachtGame::setQaStationaryCupPresentation() {
    host_.stop();
    rollAnimation_.stop();
    gestureAnimation_.stop();
    outcomeAnimation_.stop();
    introPhase_ = IntroPhase::Complete;
    openingDelayMilliseconds_ = 0;
    introGapSourceTicks_ = 0;
    showComputerDice_ = false;
    pendingComputerAfterSpeech_ = false;
    pendingScoreReactionMovie_ = -1;
    pendingComputerRerollSpeech_ = false;
    rolls_ = 0;
    round_ = 0;
    winner_ = 0;
    pendingRollPlayer_ = 0;
    settlingDieIndex_ = 0;
    computerAttempt_ = 0;
    computerRerollStage_ = 0;
    outcomePhase_ = OutcomePhase::None;
    held_.fill(false);
    dice_.fill(1);
    status_.clear();
    cancelSourceIdle();
}

void YachtGame::setQaComputerDicePresentation() {
    setQaStationaryCupPresentation();
    // Retained vanilla trace 7: Mario has completed his first roll, two
    // small remaining-roll markers are visible, and all five dice are still
    // white. This is a stable frame immediately before his reroll gesture.
    humanScores_.fill(-1);
    computerScores_.fill(-1);
    computerAttempt_ = 1;
    showComputerDice_ = true;
    dice_ = {4, 2, 2, 3, 4};
    held_.fill(false);
    status_.clear();
}

void YachtGame::setQaRerollGesturePresentation(std::uint32_t sourceTime) {
    setQaStationaryCupPresentation();
    // Match the independently captured vanilla third-attempt gesture: two
    // white dice followed by three held red dice, empty scorecards, and no
    // remaining-roll markers. This isolates movie 6021's registration without
    // manufacturing presentation state that was absent from the source frame.
    humanScores_.fill(-1);
    computerScores_.fill(-1);
    computerAttempt_ = 3;
    showComputerDice_ = true;
    dice_ = {4, 2, 3, 3, 4};
    held_ = {false, false, true, true, true};
    gestureAnimation_.showFrame(6021, kMacYachtHostAnchor.x,
                                kMacYachtHostAnchor.y, sourceTime);
}

void YachtGame::setQaRollPresentation() {
    setQaStationaryCupPresentation();
    roll();
}

void YachtGame::click(Point point) {
    cancelSourceIdle();
    if (winner_ || openingDelayMilliseconds_ > 0 || pendingRollPlayer_ ||
        pendingComputerAfterSpeech_ || pendingScoreReactionMovie_ >= 0 || rollAnimation_.active() ||
        gestureAnimation_.active() || host_.active() ||
        computerRerollStage_ != 0) return;
    if (rolls_ > 0 && rolls_ < 3) {
        for (int index = 0; index < 5; ++index) {
            Rect die = yachtDieRect(index, held_[static_cast<std::size_t>(index)]);
            if (dosEdition()) {
                die = {dosX(die.left), dosY(die.top), dosX(die.right), dosY(die.bottom)};
            }
            if (die.contains(point)) {
                held_[index] = !held_[index];
                context_.audio.playSound(5028);
                return;
            }
        }
    }
    const Rect rollButton = dosEdition() ? kDosYachtRollButton : kMacYachtRollButton;
    if (rollButton.contains(point)) { roll(); return; }
    Point scorePoint = point;
    if (dosEdition()) {
        scorePoint = {point.x * kLogicalWidth / kDosLogicalWidth,
                      point.y * kLogicalHeight / kDosLogicalHeight};
    }
    if (const int category = yachtScoreCategoryAt(scorePoint); category >= 0)
        scoreHuman(category);
}

void YachtGame::render(Canvas& canvas) {
    canvas.clear(rgb(0, 0, 0));
    drawBackground(canvas, 6001);
    if (!gestureAnimation_.active()) {
        // Dialogue movies contain the head only, so Pak 6012 is their fixed
        // torso/hand underlay. The neutral actor is movie 6021 at source time
        // zero, not raw Pak frame zero: its simultaneous overlay cel restores
        // Mario's left glove. Drawing all actor paths at once duplicates him;
        // drawing 6012 after the live head covers his jaw.
        if (host_.active()) {
            canvas.sprite(context_.graphics.sprite(6012),
                          dosEdition() ? 119 : kMacYachtTorsoAnchor.x,
                          dosEdition() ? 51 : kMacYachtTorsoAnchor.y, false);
            (void)host_.render(canvas);
        } else {
            idleActorMovie_.render(canvas, context_.graphics, 0,
                                   dosEdition() ? kDosYachtIdleMovieAnchor.x
                                                : kMacYachtIdleMovieAnchor.x,
                                   dosEdition() ? kDosYachtIdleMovieAnchor.y
                                                : kMacYachtIdleMovieAnchor.y);
        }
    } else {
        (void)gestureAnimation_.render(canvas);
    }
    (void)rollAnimation_.render(canvas);
    if (shouldDrawStationaryCup())
        canvas.sprite(context_.graphics.sprite(6010, 12),
                      dosEdition() ? 136 : kMacYachtCupAnchor.x,
                      dosEdition() ? 86 : kMacYachtCupAnchor.y, false);
    canvas.pakText(context_.graphics,
                   context_.playerName.empty() ? L"PLAYER" : context_.playerName,
                   226, dosEdition() ? Rect{236, 9, 313, 27} : Rect{378, 20, 499, 47},
                   DT_CENTER | DT_VCENTER | DT_SINGLELINE, 11);
    const bool computerSelectionVisible = computerAttempt_ > 0 && pendingRollPlayer_ == 0 &&
                                          !rollAnimation_.active();
    const bool diceVisible = rolls_ > 0 || showComputerDice_ || computerSelectionVisible ||
                             pendingRollPlayer_ != 0;
    if (diceVisible) for (int index = 0; index < 5; ++index) {
        if (outcomePhase_ == OutcomePhase::VictoryDice && index >= outcomeVisibleDiceCount_)
            continue;
        const std::size_t dieIndex = static_cast<std::size_t>(index);
        const bool firstRoll = pendingRollPlayer_ > 0 ? rolls_ == 0 : computerAttempt_ == 0;
        const bool rerolled = firstRoll || !held_[dieIndex];
        if (pendingRollPlayer_ != 0 && rerolled &&
            (rollAnimation_.active() || index >= settlingDieIndex_)) continue;
        const int frame = std::clamp(dice_[dieIndex] - 1 + (held_[dieIndex] ? 6 : 0), 0, 11);
        Rect rect = yachtDieRect(index, held_[dieIndex]);
        if (dosEdition()) {
            rect = {dosX(rect.left), dosY(rect.top), dosX(rect.right), dosY(rect.bottom)};
        }
        canvas.sprite(context_.graphics.sprite(6010, frame), rect.left, rect.top, false);
    }
    if (introPhase_ == IntroPhase::Complete && !winner_) {
        const bool computerTurn = pendingRollPlayer_ < 0 || computerAttempt_ > 0 ||
                                  computerRerollStage_ != 0 || pendingComputerAfterSpeech_;
        if (computerTurn && !pendingComputerAfterSpeech_ && computerRerollStage_ != 8) {
            const int remaining = yachtRemainingRollMarkers(
                computerAttempt_, pendingRollPlayer_ < 0);
            for (int index = 0; index < remaining; ++index)
                canvas.sprite(context_.graphics.sprite(6010, 13),
                              (dosEdition() ? 92 : 147) + (dosEdition() ? 17 : 27) * index,
                              dosEdition() ? 95 : 182, false);
        } else if (!computerTurn) {
            const int remaining = yachtRemainingRollMarkers(rolls_, pendingRollPlayer_ > 0);
            for (int index = 0; index < remaining; ++index)
                canvas.sprite(context_.graphics.sprite(6010, 14),
                              (dosEdition() ? 256 : 409) + (dosEdition() ? 20 : 33) * index,
                              dosEdition() ? 171 : 328, false);
        }
    }
    (void)outcomeAnimation_.render(canvas);
    for (int category = 0; category < 12; ++category) {
        const int row = 11 - category;
        // $30EE stores the score baseline at 60 + 20*row.  A 20-pixel
        // native row preserves that source pitch without accumulating drift.
        const int top = dosEdition() ? 27 + row * 12 : 52 + row * kPlayerScoreLineHeight;
        const auto show = [](int value) { return value < 0 ? std::wstring() : std::to_wstring(value); };
        canvas.pakText(context_.graphics, show(computerScores_[category]), 226,
                       dosEdition() ? Rect{68, top, 98, top + 10}
                                    : Rect{109, top, 135, top + 18});
        canvas.pakText(context_.graphics, show(humanScores_[category]), 226,
                       dosEdition() ? Rect{290, top, 317, top + 10}
                                    : Rect{475, top, 502, top + 18});
    }
    canvas.pakText(context_.graphics, std::to_wstring(total(computerScores_)), 226,
                   dosEdition() ? Rect{57, 151, 98, 163} : Rect{91, 289, 135, 313},
                   DT_RIGHT | DT_VCENTER | DT_SINGLELINE);
    canvas.pakText(context_.graphics, std::to_wstring(total(humanScores_)), 226,
                   dosEdition() ? Rect{286, 151, 317, 163} : Rect{458, 289, 502, 313},
                   DT_RIGHT | DT_VCENTER | DT_SINGLELINE);
    canvas.pakText(context_.graphics, status_, 224,
                   dosEdition() ? Rect{3, 188, 317, 200} : Rect{5, 359, 507, 383});
}

}  // namespace mf
